ar =
  signIn: "تسجيل الدخول"
  signin: "تسجيل الدخول"
  signOut: "تسجيل الخروج"
  signUp: "افتح حساب جديد"
  OR: "او"
  forgotPassword: "نسيت كلمة السر؟"
  emailAddress: "البريد الالكترونى"
  emailResetLink: "اعادة تعيين البريد الالكترونى"
  dontHaveAnAccount: "ليس عندك حساب؟"
  resetYourPassword: "اعادة تعيين كلمة السر"
  updateYourPassword: "جدد كلمة السر"
  password: "كلمة السر"
  usernameOrEmail: "اسم المستخدم او البريد الالكترونى"
  email: "البريد الالكترونى"
  ifYouAlreadyHaveAnAccount: "اذا كان عندك حساب"
  signUpWithYourEmailAddress: "سجل ببريدك الالكترونى"
  username: "اسم المستخدم"
  optional: "اختيارى"
  signupCode: "رمز التسجيل"
  clickAgree: "بفتح حسابك انت توافق على"
  privacyPolicy: "سياسة الخصوصية"
  terms: "شروط الاستخدام"
  sign: "تسجيل"
  configure: "تعديل"
  with: "مع"
  createAccount: "افتح حساب جديد"
  verificationPending: "Confirm your email address"
  verificationPendingDetails: "A confirmation email has been sent to the email address you provided. Click on the confirmation link in the email to activate your account."
  and: "و"
  "Match failed":  "المطابقة فشلت"
  "User not found":  "اسم المستخدم غير موجود"

  error:
    minChar: "سبعة حروف هو الحد الادنى لكلمة السر"
    pwOneLetter: "كلمة السر تحتاج الى حرف اخر"
    pwOneDigit: "كلمة السر يجب ان تحتوى على رقم واحد على الاقل"
    usernameRequired: "اسم المستخدم مطلوب"
    emailRequired: "البريد الالكترونى مطلوب"
    signupCodeRequired: "رمز التسجيل مطلوب"
    signupCodeIncorrect: "رمز التسجيل غير صحيح"
    signInRequired: "عليك بتسجبل الدخول لفعل ذلك"
    usernameIsEmail: "اسم المستخدم لا يمكن ان يكون بريد الكترونى"

T9n.map "ar", ar
