zh_tw =
  signIn: "登入"
  signin: "登入"
  signOut: "登出"
  signUp: "註冊"
  OR: "或"
  forgotPassword: "忘記密碼?"
  emailAddress: "電子郵件地址"
  emailResetLink: "電子郵件重設連結"
  dontHaveAnAccount: "還沒有賬戶?"
  resetYourPassword: "重置您的密碼"
  updateYourPassword: "更新您的密碼"
  password: "密碼"
  usernameOrEmail: "用戶名或電子郵件地址"
  email: "電子郵件"
  ifYouAlreadyHaveAnAccount: "如果你已經有一個帳戶"
  signUpWithYourEmailAddress: "用您的郵箱地址註冊"
  username: "用戶名"
  optional: "可選項"
  signupCode: "註冊碼"
  clickAgree: "點擊註冊，您同意我們的"
  privacyPolicy: "隱私政策"
  terms: "使用條款"
  sign: "註冊"
  configure: "設定"
  with: "與"
  createAccount: "創建帳戶"
  and: "和"
  "Match failed":  "配對失敗"
  "User not found":  "找不到用戶"

  error:
    minChar: "密碼最小7個字符。"
    pwOneLetter: "密碼需要1個字母。"
    pwOneDigit: "密碼必須至少有一個數字。"
    usernameRequired: "用戶名是必需的。"
    emailRequired: "電子郵件是必需的。"
    signupCodeRequired: "註冊碼是必需的。"
    signupCodeIncorrect: "註冊碼不正確。"
    signInRequired: "您必須先登錄才能進行此操作。"
    usernameIsEmail: "用戶名不能為電子郵件地址。"

T9n.map "zh_tw", zh_tw
