zh_cn =
  signIn: "登录"
  signin: "登录"
  signOut: "注销"
  signUp: "注册"
  OR: "或"
  forgotPassword: "忘记密码？"
  emailAddress: "邮箱地址"
  emailResetLink: "邮箱重置链接"
  dontHaveAnAccount: "还没有账户？"
  resetYourPassword: "重置您的密码"
  updateYourPassword: "更新您的密码"
  password: "密码"
  usernameOrEmail: "用户名或邮箱"
  email: "邮箱"
  ifYouAlreadyHaveAnAccount: "如果您已经拥有一个账户"
  signUpWithYourEmailAddress: "用您的邮箱地址注册"
  username: "用户名"
  optional: "可选项"
  signupCode: "注册码"
  clickAgree: "点击注册后，您同意我们的"
  privacyPolicy: "私有条款"
  terms: "使用术语"
  sign: "标记"
  configure: "配置"
  with: "与"
  createAccount: "建立一个账户"
  and: "和"
  "Match failed":  "匹配失败"
  "User not found":  "用户不存在"

  error:
    minChar: "密码至少7个字母。"
    pwOneLetter: "密码需要一个词。"
    pwOneDigit: "密码必须至少有一个数字。"
    usernameRequired: "要求用户名。"
    emailRequired: "要求邮箱。"
    signupCodeRequired: "要求注册码。"
    signupCodeIncorrect: "注册码错误。"
    signInRequired: "您必须登录才能进行此操作。"
    usernameIsEmail: "用户名不能是一个邮箱地址"

T9n.map "zh_cn", zh_cn
