he =
  signIn: "כניסה לחשבון"
  signin: "כניסה לחשבון"
  signOut: "יציאה"
  signUp: "חשבון חדש"
  OR: "או"
  forgotPassword: "שחכת סיסמא?"
  emailAddress: "כתובת Email"
  emailResetLink: "קישור לאיפוס Email"
  dontHaveAnAccount: "אין לך חשבון?"
  resetYourPassword: "איפוס סיסמא"
  updateYourPassword: "עדכון סיסמא"
  password: "סיסמא"
  usernameOrEmail: "שם משתמש או Email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "אם יש לך חשבון"
  signUpWithYourEmailAddress: "הירשם עם כתובת ה-Email"
  username: "שם משתמש"
  optional: "שדה רשות"
  signupCode: "קוד הרשמה"
  clickAgree: "על ידי סיום תהליך ההרשמה, הינך מסכים"
  privacyPolicy: "לתנאי הפרטיות"
  terms: "לתנאי השימוש"
  sign: "הירשם"
  configure: "הגדרות"
  with: "עם"
  createAccount: "חשבון חדש"
  and: "ו"
  "Match failed":  "התאמה נכשלה (Match Failed)"
  "User not found":  "המשתמש לא נמצא"

  error:
    minChar: "הסיסמה חייבת לכלול 7 תווים."
    pwOneLetter: "הסיסמה חייבת לכלות אות אחת."
    pwOneDigit: "הסיסמה חייבת לכלות מספר אחד."
    usernameRequired: "חובה להזין שם משתמש."
    emailRequired: "חובה להזין Email."
    signupCodeRequired: "חובה להזין קוד הרשמה."
    signupCodeIncorrect: "קוד ההרשמה שגוי."
    signInRequired: "אין לך רשות לבצע פעולה זאת."
    usernameIsEmail: "שם המשתמש לא יכול להיות כתובת Email."

T9n.map "he", he
