ja =
  signIn: "ログイン"
  signin: "ログイン"
  signOut: "ログアウト"
  signUp: "登録"
  OR: "OR"
  forgotPassword: "パスワード忘れた？"
  emailAddress: "メールアドレス"
  emailResetLink: "メールリセット"
  dontHaveAnAccount: "まだ登録していない？"
  resetYourPassword: "パスワードリセット"
  updateYourPassword: "パスワード更新"
  password: "パスワード"
  usernameOrEmail: "ユーザー名前かメールアドレス"
  email: "メールアドレス"
  ifYouAlreadyHaveAnAccount: "既に登録している方"
  signUpWithYourEmailAddress: "メールアドレスで登録する"
  username: "ユーザー名"
  optional: "随意"
  signupCode: "登録コード"
  clickAgree: "登録をクリックすると、規約に同意する"
  privacyPolicy: "プライバシー規約"
  terms: "利用契約"
  sign: "サイン"
  configure: "設定"
  with: "と"
  createAccount: "新規登録"
  and: "と"
  "Match failed":  "Match failed"
  "User not found":  "ユーザーが見つからない"

  error:
    minChar: "7文字が必要"
    pwOneLetter: "アルファベット文字が必要"
    pwOneDigit: "パスワードに数字が必要"
    usernameRequired: "ユーザー名が必要"
    emailRequired: "めーるアドレスが必要"
    signupCodeRequired: "登録コードが必要."
    signupCodeIncorrect: "登録コードの誤りがあるようです"
    signInRequired: "ログインが必要"
    usernameIsEmail: "ユーザー名ではメアドレスは使えない"

T9n.map "ja", ja
