ja =
  signIn: "ログイン"
  signin: "ログイン"
  signOut: "ログアウト"
  signUp: "アカウント登録"
  OR: "または"
  forgotPassword: "パスワードをお忘れですか?"
  emailAddress: "メールアドレス"
  emailResetLink: "パスワードリセットのメールを送る"
  dontHaveAnAccount: "まだアカウントを登録していませんか?"
  resetYourPassword: "パスワードをリセットする"
  updateYourPassword: "パスワードを変更する"
  password: "パスワード"
  usernameOrEmail: "ユーザ名またはメールアドレス"
  email: "メールアドレス"
  ifYouAlreadyHaveAnAccount: "既にアカウントをお持ちの場合は"
  signUpWithYourEmailAddress: "メールアドレスでアカウントを登録する"
  username: "ユーザ名"
  optional: "任意"
  signupCode: "登録用コード"
  clickAgree: "登録ボタンを押すことで、あなたは次の内容に同意したことになります："
  privacyPolicy: "プライバシーポリシー"
  terms: "利用規約"
  sign: "署名"
  configure: "設定"
  with: "："
  createAccount: "アカウントを登録する"
  verificationPending: "メールアドレスの確認"
  verificationPendingDetails: "確認用メールをあなたのアドレスに送りました。メールに記載されている確認用のリンクを押して、アカウントを有効化してください。"
  and: "と"
  "Match failed":  "一致しません"
  "User not found":  "ユーザ名が見つかりません"

  error:
    minChar: "パスワードは7文字以上ご入力ください。"
    pwOneLetter: "パスワードに1文字以上のアルファベットを含めてください。"
    pwOneDigit: "パスワードに1文字以上の数字を含めてください。"
    usernameRequired: "ユーザ名を入力してください。"
    emailRequired: "メールアドレスを入力してください。"
    signupCodeRequired: "登録用コードを入力してください。"
    signupCodeIncorrect: "登録用コードが間違っています。"
    signInRequired: "ログインが必要です。"
    usernameIsEmail: "ユーザ名にメールアドレスを入力しないでください。"

T9n.map "ja", ja
