nb =
  signIn: "Logg in"
  signin: "logg in"
  signOut: "Logg ut"
  signUp: "Opprett konto"
  OR: "ELLER"
  forgotPassword: "Glemt din e-postadresse?"
  emailAddress: "E-postadresse"
  emailResetLink: "E-post tilbakestillingslenke"
  dontHaveAnAccount: "Har du ikke konto?"
  resetYourPassword: "Tilbakestill passord"
  updateYourPassword: "Oppdater passord"
  password: "Passord"
  usernameOrEmail: "Brukernavn eller e-postadresse"
  email: "E-postadresse"
  ifYouAlreadyHaveAnAccount: "Om du allerede har konto"
  signUpWithYourEmailAddress: "Opprett konto med din e-postadresse"
  username: "Brukernavn"
  optional: "Valgfritt"
  signupCode: "Registreringskode"
  clickAgree: "När du velger å opprette en konto så godkenner du også våre"
  privacyPolicy: "personvernsregler"
  terms: "brukervilkår"
  sign: "Logg"
  configure: "Konfigurer"
  with: "med"
  createAccount: "Opprett konto"
  and: "og"
  "Match failed":  "Ikke samsvar"
  "User not found":  "Bruker ikke funnet"

  error:
    minChar: "Det krevs minst 7 tegn i ditt passord."
    pwOneLetter: "Passordet må ha minst én bokstav."
    pwOneDigit: "Passordet måste ha minst ett siffer."
    usernameRequired: "Brukernavn er obligatorisk."
    emailRequired: "E-postadresse kreves."
    signupCodeRequired: "Registreringskode kreves."
    signupCodeIncorrect: "Registreringskoden er feil."
    signInRequired: "Inloggning kreves her."
    usernameIsEmail: "Brukernavnet kan ikke være en e-postadress."

T9n.map "nb", nb
