pt =
  signIn: "Entrar"
  signin: "entrar"
  signOut: "Sair"
  signUp: "Cadastrar"
  OR: "Ou"
  forgotPassword: "Esqueceu sua senha?"
  emailAddress: "Email"
  emailResetLink: "Link para restaurar email"
  dontHaveAnAccount: "Não possui uma conta?"
  resetYourPassword: "Restaurar sua senha"
  updateYourPassword: "Atualize sua senha"
  password: "Senha"
  usernameOrEmail: "Usuário ou Email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Se já possui uma conta"
  signUpWithYourEmailAddress: "Cadastre-se com seu email"
  username: "Username"
  optional: "Optional"
  signupCode: "Código de Cadastro"
  clickAgree: "Clicando em cadastrar, você concorda com nossa"
  privacyPolicy: "Política de Privacidade"
  terms: "Termos de Uso"
  sign: "Ässinar"
  configure: "Configure"
  with: "com"
  createAccount: "Criar conta"
  and: "e"
  "Match failed":  "Usuário ou senha errado"
  "User not found":  "Usuário não encontrado"

  error:
    minChar: "A senha deve ter ao menos 7 caracteres."
    pwOneLetter: "Senha requer ao menos uma letra."
    pwOneDigit: "Senha requer ao menos um dígito."
    usernameRequired: "Usuário é necessário."
    emailRequired: "Email é necessário."
    signupCodeRequired: "Código de cadastro é necessário."
    signupCodeIncorrect: "Código de cadastro está incorreto."
    signInRequired: "Você deve estar logado para executar esta ação."
    usernameIsEmail: "Usuário não pode ser um endereço de email."

T9n.map "pt", pt
