pt =
  signIn: "Entrar"
  signin: "Entrar"
  signOut: "Sair"
  signUp: "Registrar"
  OR: "OU"
  forgotPassword: "Esqueceu sua senha?"
  emailAddress: "Endereço de e-mail"
  emailResetLink: "Gerar nova senha"
  dontHaveAnAccount: "Não tem conta?"
  resetYourPassword: "Gerar nova senha"
  updateYourPassword: "Atualizar senha"
  password: "Senha"
  usernameOrEmail: "Usuario ou e-mail"
  email: "E-mail"
  ifYouAlreadyHaveAnAccount: "Se você já tem uma conta"
  signUpWithYourEmailAddress: "Entre usando seu endereço de e-mail"
  username: "Nome de usuário"
  optional: "Opcional"
  signupCode: "Código de acesso"
  clickAgree: "Ao clicar em Entrar, você aceita nosso"
  privacyPolicy: "Política de Privacidade"
  terms: "Termos de Uso"
  sign: "Entrar"
  configure: "Configurar"
  with: "com"
  createAccount: "Criar Conta"
  verificationPending: "Confirm your email address"
  verificationPendingDetails: "A confirmation email has been sent to the email address you provided. Click on the confirmation link in the email to activate your account."
  and: "e"
  "Match failed":  "Usuário ou senha não encontrado"
  "User not found":  "Usuário não encontrado"

  error:
    minChar: "Senha requer um mínimo de 7 caracteres."
    pwOneLetter: "Senha deve conter pelo menos uma letra."
    pwOneDigit: "Senha deve conter pelo menos um digito."
    usernameRequired: "Nome de usuário é obrigatório."
    emailRequired: "E-mail é obrigatório."
    signupCodeRequired: "É necessário um código de acesso."
    signupCodeIncorrect: "Código de acesso incorreto."
    signInRequired: "Você precisa estar logado para fazer isso."
    usernameIsEmail: "Nome de usuário não pode ser um endereço de e-mail."

T9n.map "pt", pt
