ru =
  signIn: "Войти"
  signin: "Войти"
  signOut: "Выйти"
  signUp: "Регистрация"
  OR: "ИЛИ"
  forgotPassword: "Забыли пароль?"
  emailAddress: "Email адрес"
  emailResetLink: "Отправить email для сброса пароля"
  dontHaveAnAccount: "Нет аккаунта?"
  resetYourPassword: "Сбросить пароль"
  updateYourPassword: "Обновить пароль"
  password: "Пароль"
  usernameOrEmail: "Имя пользователя или email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Если у вас уже есть аккаунт"
  signUpWithYourEmailAddress: "Зарегистрируйтесь с вашим адресом email"
  username: "Имя пользователя"
  optional: "Необязательно"
  signupCode: "Регистрационный код"
  clickAgree: "Нажав на Регистрация вы соглашаетесь с условиями"
  privacyPolicy: "Политики безопасности"
  terms: "Условиями пользования"
  sign: "Подпись"
  configure: "Конфигурировать"
  with: "с"
  createAccount: "Создать аккаунт"
  and: "и"
  "Match failed":  "Не совпадает"
  "User not found":  "Пользователь не найден"

  error:
    minChar: "Минимальное кол-во символов для пароля 7."
    pwOneLetter: "В пароле должна быть как минимум одна буква."
    pwOneDigit: "В пароле должна быть как минимум одна цифра."
    usernameRequired: "Имя пользователя обязательно."
    emailRequired: "Email обязательно."
    signupCodeRequired: "Необходим регистрациооный код."
    signupCodeIncorrect: "Неправильный регистрационный код."
    signInRequired: "Необходимо войти для чтобы продолжить."
    usernameIsEmail: "Имя пользователя не может быть адресом email."

T9n.map "ru", ru
