sl =
  signIn: "Prijava"
  signin: "se prijavi"
  signOut: "Odjava"
  signUp: "Registracija"
  OR: "ALI"
  forgotPassword: "Pozabljeno geslo?"
  emailAddress: "Email naslov"
  emailResetLink: "Email ponastavitvena povezava"
  dontHaveAnAccount: "Nisi registriran?"
  resetYourPassword: "Ponastavi geslo"
  updateYourPassword: "Spremeni geslo"
  password: "Geslo"
  usernameOrEmail: "Uporabniško ime ali email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Če si že registriran,"
  signUpWithYourEmailAddress: "Prijava z email naslovom"
  username: "Uporabniško ime"
  optional: "Po želji"
  signupCode: "Prijavna koda"
  clickAgree: "S klikom na Registracija se strinjaš"
  privacyPolicy: "z našimi pogoji"
  terms: "Pogoji uporabe"
  sign: "Prijava"
  configure: "Nastavi"
  with: "z"
  createAccount: "Nova registracija"
  and: "in"
  "Match failed":  "Prijava neuspešna"
  "User not found":  "Uporabnik ne obstaja"

  error:
    minChar: "Geslo mora imeti vsaj sedem znakov."
    pwOneLetter: "V geslu mora biti vsaj ena črka."
    pwOneDigit: "V geslu mora biti vsaj ena številka."
    usernameRequired: "Uporabniško ime je obvezen vnos."
    emailRequired: "Email je obvezen vnos."
    signupCodeRequired: "Prijavna koda je obvezen vnos."
    signupCodeIncorrect: "Prijavna koda je napačna."
    signInRequired: "Za to morate biti prijavljeni."
    usernameIsEmail: "Uporabniško ime ne more biti email naslov."

T9n.map "sl", sl
