sl =
  signIn: "Prijava"
  signin: "se prijavi"
  signOut: "Odjava"
  signUp: "Registracija"
  OR: "ALI"
  forgotPassword: "Pozabljeno geslo?"
  emailAddress: "Email naslov"
  emailResetLink: "Pošlji ponastavitveno povezavo"
  dontHaveAnAccount: "Nisi registriran(a)?"
  resetYourPassword: "Ponastavi geslo"
  updateYourPassword: "Spremeni geslo"
  password: "Geslo"
  usernameOrEmail: "Uporabniško ime ali email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Če si že registriran(a),"
  signUpWithYourEmailAddress: "Prijava z email naslovom"
  username: "Uporabniško ime"
  optional: "Po želji"
  signupCode: "Prijavna koda"
  clickAgree: "S klikom na Registracija se strinjaš"
  privacyPolicy: "z našimi pogoji uporabe"
  terms: "Pogoji uporabe"
  sign: "Prijava"
  configure: "Nastavi"
  with: "z"
  createAccount: "Nova registracija"
  verificationPending: "Confirm your email address"
  verificationPendingDetails: "A confirmation email has been sent to the email address you provided. Click on the confirmation link in the email to activate your account."
  and: "in"
  "Match failed":  "Prijava neuspešna"
  "User not found":  "Uporabnik ne obstaja"
  "Incorrect password": "Napačno geslo"
  "Email already exists.": "Email že obstaja."
  "Email is required": "Email je obvezen podatek"
  
  error:
    minChar: "Geslo mora imeti vsaj sedem znakov."
    pwOneLetter: "V geslu mora biti vsaj ena črka."
    pwOneDigit: "V geslu mora biti vsaj ena številka."
    usernameRequired: "Uporabniško ime je obvezen vnos."
    emailRequired: "Email je obvezen vnos."
    signupCodeRequired: "Prijavna koda je obvezen vnos."
    signupCodeIncorrect: "Prijavna koda je napačna."
    signInRequired: "Za to moraš biti prijavljen(a)."
    usernameIsEmail: "Uporabniško ime ne more biti email naslov."
    
T9n.map "sl", sl
