sv =
  signIn: "Logga in"
  signin: "logga in"
  signOut: "Logga ut"
  signUp: "Skapa konto"
  OR: "ELLER"
  forgotPassword: "Glömt din e-postadress?"
  emailAddress: "E-postadress"
  emailResetLink: "E-post återställningslänk"
  dontHaveAnAccount: "Har du inget konto?"
  resetYourPassword: "Återställ ditt lösenord"
  updateYourPassword: "Uppdatera ditt lösenord"
  password: "Lösenord"
  usernameOrEmail: "Användarnamn eller e-postadress"
  email: "E-postadress"
  ifYouAlreadyHaveAnAccount: "Om du redan har ett konto"
  signUpWithYourEmailAddress: "Skapa ett konto med din e-postadress"
  username: "Användarnamn"
  optional: "Valfri"
  signupCode: "Registreringskod"
  clickAgree: "När du väljer att skapa ett konto så godkänner du också vår"
  privacyPolicy: "integritetspolicy"
  terms: "användarvilkor"
  sign: "Logga"
  configure: "Konfigurera"
  with: "med"
  createAccount: "Skapa ett konto"
  verificationPending: "Confirm your email address"
  verificationPendingDetails: "A confirmation email has been sent to the email address you provided. Click on the confirmation link in the email to activate your account."
  and: "och"
  "Match failed":  "Matchning misslyckades"
  "User not found":  "Användaren hittades inte"

  error:
    minChar: "Det krävs minst 7 tecken i ditt lösenord."
    pwOneLetter: "Lösenordet måste ha minst 1 bokstav."
    pwOneDigit: "Lösenordet måste ha minst 1 siffra."
    usernameRequired: "Det krävs ett användarnamn."
    emailRequired: "Det krävs ett lösenord."
    signupCodeRequired: "Det krävs en registreringskod."
    signupCodeIncorrect: "Registreringskoden är felaktig."
    signInRequired: "Inloggning krävs här."
    usernameIsEmail: "Användarnamnet kan inte vara en e-postadress."

T9n.map "sv", sv
