uk =
  signIn: "Ввійти"
  signin: "Ввійти"
  signOut: "Вийти"
  signUp: "Реєстрація"
  OR: "АБО"
  forgotPassword: "Забули пароль?"
  emailAddress: "Email"
  emailResetLink: "Надіслати посилання для скидання"
  dontHaveAnAccount: "Немає акаунта?"
  resetYourPassword: "Скинути пароль"
  updateYourPassword: "Оновити пароль"
  password: "Пароль"
  usernameOrEmail: "Ім'я користувача або email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Якщо у вас вже є акаунт"
  signUpWithYourEmailAddress: "Зареєструйтесь з вашим email адресом"
  username: "Ім'я користувача"
  optional: "Не обов'язково"
  signupCode: "Реєстраційний код"
  clickAgree: "Натиснувши на кнопку реєстрації ви погоджуєтесь з умовами"
  privacyPolicy: "Політика безпеки"
  terms: "Умови користування"
  sign: "Підпис"
  configure: "Налаштувати"
  with: "з"
  createAccount: "Створити аккаунт"
  verificationPending: "Підтвердити email адрес"
  verificationPendingDetails: "Підтвердження електронною поштою було надіслано на адресу електронної пошти, який ви вказали. Натисніть на посилання для підтвердження в листі, щоб активувати обліковий запис."
  and: "і"
  "Match failed":  "Не співпадають"
  "User not found":  "Користувач не знайдений"

  error:
    minChar: "Мінімальна кількість символів для пароля 7."
    pwOneLetter: "В паролі повинна бути хоча б одна буква."
    pwOneDigit: "В паролі повинна бути хоча б одна цифра."
    usernameRequired: "Ім'я користувача обов'язкове поле."
    emailRequired: "Email обов'язкове поле."
    signupCodeRequired: "Необхідний реєстраційний код."
    signupCodeIncorrect: "Неправильний реєстраційний код."
    signInRequired: "Необхідно ввійти щоб продовжити."
    usernameIsEmail: "Ім'я користувача не може бути адресом email."

T9n.map "uk", uk